=== Direct-Energy-Partners/interoperability-data-model/common-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "$comment": "This is the JSON schema for all IDM products.  Listed below are all the parameters that are common to all types of product.  Particular types of product have their own schemas defined in separate files, which must be in the same folder, or sub-folders.",
  "type": "object",
  "properties": {
    "manufacturer": { "$ref": "manufacturer-schema.json#/schema" },
    "productName": { "$ref": "productName-schema.json#/schema" },
    "productIdentifier": { "$ref": "productIdentifier-schema.json#/schema" },
    "productSeries": { "$ref": "productSeries-schema.json#/schema" },
    "datasheetHyperlink": {
      "type": "string",
      "format": "uri"
    },
    "description": {
      "type": "string",
      "minLength": 0,
      "maxLength": 65535
    },
    "distributors": { "$ref": "distributors-schema.json#/schema" },
    "systemsIntegrators": { "$ref": "distributors-schema.json#/schema" },
    "embargoedCountries": { "$ref": "embargoedCountries-schema.json#/schema" },
    "notRecommendedForNewDesigns": { "type": "boolean" },
    "typeSpecificParameters": { "$ref": "typeSpecifics-schema.json#/schema" },
    "listingAuthorities": { "$ref": "listingAuthorities-schema.json#/schema" },
    "environmental": { "$ref": "environmental-schema.json#/schema" },
    "productWarrantyYrs": { "type": "number" },
    "files": { "$ref": "files-schema.json#/schema" },
    "images": { "$ref": "images-schema.json#/schema" }

  },
  "required":["manufacturer","productIdentifier"],
  "selectionTool": {
    "$comment": "The selection tool will provide the filter and display sections with the values of those parameters listed in each of the referenced files",
    "filter": [ "manufacturer.json", "productSeries.json", "notRecommendedForNewDesigns.json", "typeSpecificParameters.json", "environmental.json" ],
    "display": [ "productIdentifier.json", "images.json", "typeSpecificParameters.json", "environmental.json", "files.json" ]
  }


}

=== Direct-Energy-Partners/interoperability-data-model/testFuse.json
{
  "$schema": "common-schema.json#/schema",
  "productName": "20mm cartridge fuse, 3A",
  "productIdentifier": "3A20",
  "productSeries": "20mm fuses",
  "datasheetHyperlink": "https://dcide.app/products/65119bd43fcac27a2e84274c",
  "description": "This is just a test file to check the validator",
  "manufacturer": {
    "coName": "Evonet Energy Ltd",
    "webHomePageURL": "www.evonet.com"
  },
  "distributors": [
    {
      "coName": "Digikey",
      "webHomePageURL": "digikey.com"
    },
    {
      "coName": "Farnell",
      "webHomePageURL": "uk.farnell.com"
    }
  ],
  "embargoedCountries": [ "Russia", "North Korea" ],
  "notRecommendedForNewDesigns": false,
  "listingAuthorities": [
    {
      "LAName": "UL",
      "LALogo": "Base64Image string of logo"
    },
    {
      "LAName": "BSI",
      "LALogo": "Base64Image string of logo"
    }
  ],
  "typeSpecificParameters": {
    "componentType": "fuse",
    "fuseType":{
      "cartridge":{
        "length":"1.25in",
        "diameter": "3mm"
        }
    },    

    "currentRating": {
      "value": 3.0,
      "units": "A"
    },
    "responseTime": "fast",
    "voltageRatingAC": "250V",
    "voltageRatingDC": {
      "value": 30,
      "units": "V"
    },
    "breakingCapacity": "1000A",
    "indicatorStyle": "none"
  }

}

=== Direct-Energy-Partners/interoperability-data-model/FusedSolar.json
{
	"$schema": "common-schema.json#/schema",
	"productIdentifier": "sfasdf",
	"productName": "sadfsdfa",
	"manufacturer": {
	    "coName": "sdadsfas",
	    "webHomePageURL": "www.evonet.com"
	},
	"typeSpecificParameters": {
	   "fuse":{
	       "breakingCapacity": "1kA",
	       "currentRating": {
	           "value": 10,
	           "units": "A"
	       }
	   },
	   "solar": {
	       "openCircuitVolts": {
	           "value": 80,
	           "units": "V"
	       },
	       "panelType": "flexible"
	   }
	   
	   
    },
    "embargoedCountries": ["UK","US"]
    
	
	
	
	
}
